# This workflow runs the StackSifter console app every hour
name: Run StackSifter Hourly

on:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore ./src/StackSifter/StackSifter.csproj

      - name: Build
        run: dotnet build --configuration Release ./src/StackSifter/StackSifter.csproj

      - name: Run StackSifter
        run: |
          if [ -f last-run.txt ]; then
            PREV=$(cat last-run.txt)
          else
            PREV=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          fi
          echo "Previous run: $PREV"
          dotnet run --project ./src/StackSifter/StackSifter.csproj --configuration Release -- "$PREV"

      - name: Persist last run information
        run: |
          NOW=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          echo "$NOW" > last-run.txt
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add last-run.txt
          git commit -m "chore: update last run timestamp [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
