# This workflow runs the StackSifter console app every hour
name: Run StackSifter Hourly

on:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore ./src/StackSifter/StackSifter.csproj

      - name: Build
        run: dotnet build --configuration Release ./src/StackSifter/StackSifter.csproj

      - name: Run StackSifter
        run: |
          # Try to checkout last-run.txt from the remote branch without switching
          git fetch origin data-run-information
          git checkout origin/data-run-information -- last-run.txt || true
          if [ -f last-run.txt ]; then
            PREV=$(cat last-run.txt)
          else
            PREV=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          fi
          # Optionally revert the file after use
          git restore last-run.txt || true
          dotnet run --project ./src/StackSifter/StackSifter.csproj --configuration Release -- "$PREV"

      - name: Persist last run information
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin data-run-information || git checkout -b data-run-information
          git checkout -B data-run-information origin/data-run-information || git checkout -b data-run-information
          # Update last-run.txt and commit it to the data-run-information branch only
          NOW=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          echo "$NOW" > last-run.txt
          git add last-run.txt
          git commit -m "chore: update last run timestamp [skip ci]" || echo "No changes to commit"
          git pull --rebase origin data-run-information || git push origin data-run-information
          echo "Last run timestamp updated to: $NOW"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
